#!/usr/bin/expect -f
set timeout 10
spawn ssh su594661@access-5019523613.webspace-host.com
expect {
    "password:" { send "Yassine.2011\r" }
    "(yes/no)?" { send "yes\r"; exp_continue }
}
expect -re {[$#] ?$}
send "sed -i 's/~150 MB/~150 MB (Mis à jour le 3 Mars 2026 à 07:55)/g' elazya/success.html\r"
expect -re {[$#] ?$}
send "grep 'Mis à jour' elazya/success.html\r"
expect -re {[$#] ?$}
send "exit\r"
