#!/usr/bin/expect -f
set timeout 10
spawn sftp su594661@access-5019523613.webspace-host.com
expect {
    "password:" { send "Yassine.2011\r" }
    "(yes/no)?" { send "yes\r"; exp_continue }
}
expect "sftp>"
send "put insert_key.php\r"
expect "sftp>"
send "quit\r"

spawn ssh su594661@access-5019523613.webspace-host.com
expect {
    "password:" { send "Yassine.2011\r" }
    "(yes/no)?" { send "yes\r"; exp_continue }
}
expect -re {[$#] ?$}
send "php insert_key.php\r"
expect -re {[$#] ?$}
send "exit\r"
