#!/usr/bin/expect -f
set timeout 60
spawn ssh su594661@access-5019523613.webspace-host.com
expect {
    "password:" { send "Yassine.2011\r" }
    "(yes/no)?" { send "yes\r"; exp_continue }
}
expect -re {[$#] ?$}
send "echo '--- ROOT start ---'\r"
send "cat success.html\r"
send "echo '--- ROOT end ---'\r"
send "echo '--- SUBDIR start ---'\r"
send "cat elazya/success.html\r"
send "echo '--- SUBDIR end ---'\r"
expect -re {[$#] ?$}
send "exit\r"
