#!/usr/bin/expect -f
set timeout 30
spawn ssh su594661@access-5019523613.webspace-host.com
expect {
    "password:" { send "Yassine.2011\r" }
    "(yes/no)?" { send "yes\r"; exp_continue }
}
expect -re {[$#] ?$}

send "ps aux | grep node\r"
expect -re {[$#] ?$}

send "ls -F elazya-server/\r"
expect -re {[$#] ?$}

send "cat elazya-server/stdout.log\r"
expect -re {[$#] ?$}

send "cat elazya-server/stderr.log\r"
expect -re {[$#] ?$}

send "exit\r"
