#!/usr/bin/expect -f
set timeout 30
spawn ssh su594661@access-5019523613.webspace-host.com
expect {
    "password:" { send "Yassine.2011\r" }
    "(yes/no)?" { send "yes\r"; exp_continue }
}
expect -re {[$#] ?$}

# Create test files
send "echo 'ROOT' > test_root.html\r"
expect -re {[$#] ?$}

send "mkdir -p elazya\r"
expect -re {[$#] ?$}
send "echo 'ELAZYA' > elazya/test_elazya.html\r"
expect -re {[$#] ?$}

send "exit\r"
