#!/usr/bin/expect -f
set timeout 30
spawn ssh su594661@access-5019523613.webspace-host.com
expect {
    "password:" { send "Yassine.2011\r" }
    "(yes/no)?" { send "yes\r"; exp_continue }
}
expect -re {[$#] ?$}

# Fix perms
send "chmod 755 hello.html\r"
expect -re {[$#] ?$}
send "chmod 755 index.html\r"
expect -re {[$#] ?$}
send "chmod 755 info.php\r"
expect -re {[$#] ?$}
send "chmod 755 .\r"
expect -re {[$#] ?$}

send "exit\r"
