#!/usr/bin/expect -f
set timeout 60
spawn ssh su594661@access-5019523613.webspace-host.com
expect "password:"
send "Yassine.2011\r"
expect -re {[$#] ?$}

send "cat << 'END' > ~/elazya/.htaccess
Options -MultiViews
RewriteEngine On

RewriteRule ^api/(.*)$ http://127.0.0.1:3001/api/$1 [P,L]

RewriteCond %{THE_REQUEST} \s/([^.]+)\.html [NC]
RewriteRule ^ %1 [R=301,L]

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME}.html -f
RewriteRule ^ %{REQUEST_URI}.html [L]

ErrorDocument 404 /404.html
END\r"
expect -re {[$#] ?$}

send "curl -sI http://127.0.0.1:3001/api/checkout\r"
expect -re {[$#] ?$}
send "curl -sI https://elazya.com/api/checkout\r"
expect -re {[$#] ?$}

send "exit\r"
