#!/usr/bin/expect -f
set timeout 30
spawn ssh su594661@access-5019523613.webspace-host.com
expect {
    "password:" { send "Yassine.2011\r" }
    "(yes/no)?" { send "yes\r"; exp_continue }
}
expect -re {[$#] ?$}

send "cd elazya-server\r"
expect -re {[$#] ?$}

# Force path
send "export PRISMA_QUERY_ENGINE_LIBRARY=/home/www/elazya-server/node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node\r"
expect -re {[$#] ?$}

send "node check_prisma.js\r"
expect -re {[$#] ?$}

send "exit\r"
