#!/usr/bin/expect -f
set timeout 30
spawn ssh su594661@access-5019523613.webspace-host.com
expect {
    "password:" { send "Yassine.2011\r" }
    "(yes/no)?" { send "yes\r"; exp_continue }
}
expect -re {[$#] ?$}

send "killall -u su594661 node\r"
expect -re {[$#] ?$}

send "cd elazya-server\r"
expect -re {[$#] ?$}

# Use setsid
send "setsid node server.js > stdout.log 2> stderr.log &\r"
# Need to give it a moment
sleep 2

send "ps aux | grep node\r"
expect -re {[$#] ?$}

send "exit\r"
