#!/usr/bin/expect -f
set timeout 60
spawn ssh su594661@access-5019523613.webspace-host.com
expect {
    "password:" { send "Yassine.2011\r" }
    "(yes/no)?" { send "yes\r"; exp_continue }
}

# Go to app dir
send "cd elazya-server\r"
expect "$ "

# Run Prisma Push using LOCAL binary (avoid npx version mismatch)
# We assume node_modules was uploaded successfullly
send "./node_modules/.bin/prisma db push\r"
expect "$ "

send "exit\r"
