export const browserCoreExamples = [
  "alize browser status",
  "alize browser start",
  "alize browser stop",
  "alize browser tabs",
  "alize browser open https://example.com",
  "alize browser focus abcd1234",
  "alize browser close abcd1234",
  "alize browser screenshot",
  "alize browser screenshot --full-page",
  "alize browser screenshot --ref 12",
  "alize browser snapshot",
  "alize browser snapshot --format aria --limit 200",
  "alize browser snapshot --efficient",
  "alize browser snapshot --labels",
];

export const browserActionExamples = [
  "alize browser navigate https://example.com",
  "alize browser resize 1280 720",
  "alize browser click 12 --double",
  'alize browser type 23 "hello" --submit',
  "alize browser press Enter",
  "alize browser hover 44",
  "alize browser drag 10 11",
  "alize browser select 9 OptionA OptionB",
  "alize browser upload /tmp/file.pdf",
  'alize browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "alize browser dialog --accept",
  'alize browser wait --text "Done"',
  "alize browser evaluate --fn '(el) => el.textContent' --ref 7",
  "alize browser console --level error",
  "alize browser pdf",
];
