import { NextResponse } from "next/server"
import { headers } from "next/headers"
import Stripe from "stripe"
import { PrismaClient } from "@prisma/client"
import { Resend } from "resend"

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY as string)

const prisma = new PrismaClient()
const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(req: Request) {
    const body = await req.text()
    const headerList = await headers()
    const signature = headerList.get("stripe-signature") as string

    let event: Stripe.Event

    try {
        event = stripe.webhooks.constructEvent(
            body,
            signature,
            process.env.STRIPE_WEBHOOK_SECRET as string
        )
    } catch (err: any) {
        return new NextResponse(`Webhook Error: ${err.message}`, { status: 400 })
    }

    if (event.type === "checkout.session.completed") {
        const session = event.data.object as Stripe.Checkout.Session

        // Provision License
        try {
            const customer = await prisma.customer.create({
                data: {
                    email: session.customer_email!,
                    firstName: session.metadata?.firstName,
                    lastName: session.metadata?.lastName,
                    stripeId: session.id,
                    // licenseKey is autogenerated by @default(cuid())
                }
            })

            // Send Email
            await resend.emails.send({
                from: 'Alizé <noreply@alize.ai>',
                to: customer.email,
                subject: 'Votre Clé de Licence Alizé 🔑',
                html: `
              <h1>Merci pour votre achat !</h1>
              <p>Voici votre clé de licence perpétuelle :</p>
              <pre style="background: #f4f4f4; padding: 10px; border-radius: 5px;">${customer.licenseKey}</pre>
              <p>Télécharger : <a href="https://alize.ai/download">https://alize.ai/download</a></p>
            `
            })

        } catch (dbError) {
            console.error("DB/Email Error", dbError)
            return new NextResponse("Server Error", { status: 500 })
        }
    }

    return NextResponse.json({ received: true })
}
