import { NextResponse } from "next/server"
import { stripe } from "@/lib/stripe"

// Plan pricing — uses real Stripe Price IDs
// Auto-generated by scripts/setup-stripe-products.js on 2026-02-19
const STRIPE_PRICE_IDS: Record<string, string> = {
    solo:                    "price_1T2PcdPd8IAbTjBgFbw7RE5f",
    pro:                     "price_1T2PcePd8IAbTjBg3gZE8jpS",
    business:                "price_1T2PcePd8IAbTjBgpLLr20P0",
    "upgrade-solo-pro":      "price_1T2PcfPd8IAbTjBgrUz1scrr",
    "upgrade-pro-business":  "price_1T2PcfPd8IAbTjBggfeyPZ8W",
}

const PRICES: Record<string, { amount: number; name: string; planCode: string; mode: "payment" | "subscription"; stripePriceId: string }> = {
    solo: { amount: 19700, name: "Elazya Solo (Licence à vie)", planCode: "solo", mode: "payment", stripePriceId: STRIPE_PRICE_IDS.solo },
    pro: { amount: 49700, name: "Elazya Pro (Licence à vie)", planCode: "pro", mode: "payment", stripePriceId: STRIPE_PRICE_IDS.pro },
    business: { amount: 99700, name: "Elazya Business (Licence à vie)", planCode: "business", mode: "payment", stripePriceId: STRIPE_PRICE_IDS.business },
    "upgrade-solo-pro": { amount: 30000, name: "Upgrade Solo → Pro", planCode: "pro", mode: "payment", stripePriceId: STRIPE_PRICE_IDS["upgrade-solo-pro"] },
    "upgrade-pro-business": { amount: 50000, name: "Upgrade Pro → Business", planCode: "business", mode: "payment", stripePriceId: STRIPE_PRICE_IDS["upgrade-pro-business"] },
}

export async function POST(req: Request) {
    try {
        const { email, firstName, lastName, plan, source } = await req.json()

        const selectedPlan = PRICES[plan as keyof typeof PRICES] || PRICES.solo
        const isSubscription = selectedPlan.mode === "subscription"
        const isUpgrade = plan.startsWith("upgrade-")

        // For upgrades from the app, redirect back to the app via deep link
        const successUrl = isUpgrade && source === "app"
            ? `elazya://upgrade-success?plan=${selectedPlan.planCode}&session={CHECKOUT_SESSION_ID}`
            : `${process.env.NEXT_PUBLIC_SITE_URL}/success?session_id={CHECKOUT_SESSION_ID}`

        const cancelUrl = isUpgrade && source === "app"
            ? `elazya://upgrade-cancelled`
            : `${process.env.NEXT_PUBLIC_SITE_URL}/checkout?plan=${plan}`

        const session = await stripe.checkout.sessions.create({
            payment_method_types: ["card"],
            line_items: [
                {
                    price: selectedPlan.stripePriceId,
                    quantity: 1,
                },
            ],
            mode: isSubscription ? "subscription" : "payment",
            success_url: successUrl,
            cancel_url: cancelUrl,
            customer_email: email,
            metadata: {
                firstName,
                lastName,
                plan: selectedPlan.planCode,
                isUpgrade: isUpgrade ? "true" : "false",
            },
        })

        return NextResponse.json({ url: session.url })
    } catch (err: any) {
        console.error("Stripe Checkout Error:", err)
        return NextResponse.json({ error: err.message }, { status: 500 })
    }
}
